development:
  :key: 'Uo5ehu0ZVJIkwN4y' 
  :password: 'KXOH9K5coupax3FF4bM1opp9M'
  :account_number: '510087046'
  :meter: '118564789' 
  :mode: 'test' 
  
production:  
  :key: 'xxx' 
  :password: 'xxx'
  :account_number: 'xxx'
  :meter: 'xxx' 
  :mode: 'production'